/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CreateMessageRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateDmConversationRequest
 */
public class CreateDmConversationRequestTest {
    private final CreateDmConversationRequest model = new CreateDmConversationRequest();

    /**
     * Model tests for CreateDmConversationRequest
     */
    @Test
    public void testCreateDmConversationRequest() {
        // TODO: test CreateDmConversationRequest
    }

    /**
     * Test the property 'conversationType'
     */
    @Test
    public void conversationTypeTest() {
        // TODO: test conversationType
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'participantIds'
     */
    @Test
    public void participantIdsTest() {
        // TODO: test participantIds
    }

}
