/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateDmEventResponseData
 */
public class CreateDmEventResponseDataTest {
    private final CreateDmEventResponseData model = new CreateDmEventResponseData();

    /**
     * Model tests for CreateDmEventResponseData
     */
    @Test
    public void testCreateDmEventResponseData() {
        // TODO: test CreateDmEventResponseData
    }

    /**
     * Test the property 'dmConversationId'
     */
    @Test
    public void dmConversationIdTest() {
        // TODO: test dmConversationId
    }

    /**
     * Test the property 'dmEventId'
     */
    @Test
    public void dmEventIdTest() {
        // TODO: test dmEventId
    }

}
