/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DmEventDataReferencedTweetsInner
 */
public class DmEventDataReferencedTweetsInnerTest {
    private final DmEventDataReferencedTweetsInner model = new DmEventDataReferencedTweetsInner();

    /**
     * Model tests for DmEventDataReferencedTweetsInner
     */
    @Test
    public void testDmEventDataReferencedTweetsInner() {
        // TODO: test DmEventDataReferencedTweetsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
