/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.DmEventDataAttachments;
import org.openapitools.client.model.DmEventDataReferencedTweetsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DmEventData
 */
public class DmEventDataTest {
    private final DmEventData model = new DmEventData();

    /**
     * Model tests for DmEventData
     */
    @Test
    public void testDmEventData() {
        // TODO: test DmEventData
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'dmConversationId'
     */
    @Test
    public void dmConversationIdTest() {
        // TODO: test dmConversationId
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'participantIds'
     */
    @Test
    public void participantIdsTest() {
        // TODO: test participantIds
    }

    /**
     * Test the property 'referencedTweets'
     */
    @Test
    public void referencedTweetsTest() {
        // TODO: test referencedTweets
    }

    /**
     * Test the property 'senderId'
     */
    @Test
    public void senderIdTest() {
        // TODO: test senderId
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

}
