/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DmMediaAttachment
 */
public class DmMediaAttachmentTest {
    private final DmMediaAttachment model = new DmMediaAttachment();

    /**
     * Model tests for DmMediaAttachment
     */
    @Test
    public void testDmMediaAttachment() {
        // TODO: test DmMediaAttachment
    }

    /**
     * Test the property 'mediaId'
     */
    @Test
    public void mediaIdTest() {
        // TODO: test mediaId
    }

}
