/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Get2DmConversationsIdDmEventsResponseMeta
 */
public class Get2DmConversationsIdDmEventsResponseMetaTest {
    private final Get2DmConversationsIdDmEventsResponseMeta model = new Get2DmConversationsIdDmEventsResponseMeta();

    /**
     * Model tests for Get2DmConversationsIdDmEventsResponseMeta
     */
    @Test
    public void testGet2DmConversationsIdDmEventsResponseMeta() {
        // TODO: test Get2DmConversationsIdDmEventsResponseMeta
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

    /**
     * Test the property 'previousToken'
     */
    @Test
    public void previousTokenTest() {
        // TODO: test previousToken
    }

    /**
     * Test the property 'resultCount'
     */
    @Test
    public void resultCountTest() {
        // TODO: test resultCount
    }

}
