/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Specifies the type of attachments (if any) present in this DM.
 */
@ApiModel(description = "Specifies the type of attachments (if any) present in this DM.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-22T18:08:52.595492+08:00[Asia/Hong_Kong]")
public class DmEventDataAttachments {
  public static final String SERIALIZED_NAME_CARD_IDS = "card_ids";
  @SerializedName(SERIALIZED_NAME_CARD_IDS)
  private List<String> cardIds = null;

  public static final String SERIALIZED_NAME_MEDIA_KEYS = "media_keys";
  @SerializedName(SERIALIZED_NAME_MEDIA_KEYS)
  private List<String> mediaKeys = null;

  public DmEventDataAttachments() {
  }

  public DmEventDataAttachments cardIds(List<String> cardIds) {
    
    this.cardIds = cardIds;
    return this;
  }

  public DmEventDataAttachments addCardIdsItem(String cardIdsItem) {
    if (this.cardIds == null) {
      this.cardIds = new ArrayList<>();
    }
    this.cardIds.add(cardIdsItem);
    return this;
  }

   /**
   * A list of card IDs (if cards are attached).
   * @return cardIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of card IDs (if cards are attached).")

  public List<String> getCardIds() {
    return cardIds;
  }


  public void setCardIds(List<String> cardIds) {
    this.cardIds = cardIds;
  }


  public DmEventDataAttachments mediaKeys(List<String> mediaKeys) {
    
    this.mediaKeys = mediaKeys;
    return this;
  }

  public DmEventDataAttachments addMediaKeysItem(String mediaKeysItem) {
    if (this.mediaKeys == null) {
      this.mediaKeys = new ArrayList<>();
    }
    this.mediaKeys.add(mediaKeysItem);
    return this;
  }

   /**
   * A list of Media Keys for each one of the media attachments (if media are attached).
   * @return mediaKeys
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of Media Keys for each one of the media attachments (if media are attached).")

  public List<String> getMediaKeys() {
    return mediaKeys;
  }


  public void setMediaKeys(List<String> mediaKeys) {
    this.mediaKeys = mediaKeys;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DmEventDataAttachments dmEventDataAttachments = (DmEventDataAttachments) o;
    return Objects.equals(this.cardIds, dmEventDataAttachments.cardIds) &&
        Objects.equals(this.mediaKeys, dmEventDataAttachments.mediaKeys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardIds, mediaKeys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DmEventDataAttachments {\n");
    sb.append("    cardIds: ").append(toIndentedString(cardIds)).append("\n");
    sb.append("    mediaKeys: ").append(toIndentedString(mediaKeys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("card_ids");
    openapiFields.add("media_keys");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DmEventDataAttachments
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DmEventDataAttachments.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DmEventDataAttachments is not found in the empty JSON string", DmEventDataAttachments.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!DmEventDataAttachments.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DmEventDataAttachments` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("card_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_ids` to be an array in the JSON string but got `%s`", jsonObj.get("card_ids").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("media_keys").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `media_keys` to be an array in the JSON string but got `%s`", jsonObj.get("media_keys").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DmEventDataAttachments.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DmEventDataAttachments' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DmEventDataAttachments> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DmEventDataAttachments.class));

       return (TypeAdapter<T>) new TypeAdapter<DmEventDataAttachments>() {
           @Override
           public void write(JsonWriter out, DmEventDataAttachments value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DmEventDataAttachments read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DmEventDataAttachments given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DmEventDataAttachments
  * @throws IOException if the JSON string is invalid with respect to DmEventDataAttachments
  */
  public static DmEventDataAttachments fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DmEventDataAttachments.class);
  }

 /**
  * Convert an instance of DmEventDataAttachments to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

